version: "3.8"

services:
  RIMasterDatabase:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: RIMasterDatabase
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - VITE_PORT=${VITE_PORT}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:7000",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  app-network:
    driver: bridge
