/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangLangRouteImport } from './routes/$lang/_lang'
import { Route as LangLangIndexRouteImport } from './routes/$lang/_lang/index'
import { Route as LangLangLoginRouteImport } from './routes/$lang/_lang/login'
import { Route as LangLangGlossaryRouteImport } from './routes/$lang/_lang/glossary'
import { Route as LangLangDashboardRouteImport } from './routes/$lang/_lang/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLangRoute = LangLangRouteImport.update({
  id: '/$lang/_lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLangIndexRoute = LangLangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangLangRoute,
} as any)
const LangLangLoginRoute = LangLangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangLangRoute,
} as any)
const LangLangGlossaryRoute = LangLangGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => LangLangRoute,
} as any)
const LangLangDashboardRoute = LangLangDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangLangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangLangRouteWithChildren
  '/$lang/dashboard': typeof LangLangDashboardRoute
  '/$lang/glossary': typeof LangLangGlossaryRoute
  '/$lang/login': typeof LangLangLoginRoute
  '/$lang/': typeof LangLangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/dashboard': typeof LangLangDashboardRoute
  '/$lang/glossary': typeof LangLangGlossaryRoute
  '/$lang/login': typeof LangLangLoginRoute
  '/$lang': typeof LangLangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang/_lang': typeof LangLangRouteWithChildren
  '/$lang/_lang/dashboard': typeof LangLangDashboardRoute
  '/$lang/_lang/glossary': typeof LangLangGlossaryRoute
  '/$lang/_lang/login': typeof LangLangLoginRoute
  '/$lang/_lang/': typeof LangLangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/dashboard'
    | '/$lang/glossary'
    | '/$lang/login'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lang/dashboard' | '/$lang/glossary' | '/$lang/login' | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang/_lang'
    | '/$lang/_lang/dashboard'
    | '/$lang/_lang/glossary'
    | '/$lang/_lang/login'
    | '/$lang/_lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangLangRoute: typeof LangLangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/_lang': {
      id: '/$lang/_lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/_lang/': {
      id: '/$lang/_lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangLangIndexRouteImport
      parentRoute: typeof LangLangRoute
    }
    '/$lang/_lang/login': {
      id: '/$lang/_lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLangLoginRouteImport
      parentRoute: typeof LangLangRoute
    }
    '/$lang/_lang/glossary': {
      id: '/$lang/_lang/glossary'
      path: '/glossary'
      fullPath: '/$lang/glossary'
      preLoaderRoute: typeof LangLangGlossaryRouteImport
      parentRoute: typeof LangLangRoute
    }
    '/$lang/_lang/dashboard': {
      id: '/$lang/_lang/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangLangDashboardRouteImport
      parentRoute: typeof LangLangRoute
    }
  }
}

interface LangLangRouteChildren {
  LangLangDashboardRoute: typeof LangLangDashboardRoute
  LangLangGlossaryRoute: typeof LangLangGlossaryRoute
  LangLangLoginRoute: typeof LangLangLoginRoute
  LangLangIndexRoute: typeof LangLangIndexRoute
}

const LangLangRouteChildren: LangLangRouteChildren = {
  LangLangDashboardRoute: LangLangDashboardRoute,
  LangLangGlossaryRoute: LangLangGlossaryRoute,
  LangLangLoginRoute: LangLangLoginRoute,
  LangLangIndexRoute: LangLangIndexRoute,
}

const LangLangRouteWithChildren = LangLangRoute._addFileChildren(
  LangLangRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangLangRoute: LangLangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
