/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangLangRouteImport } from './routes/$lang/_lang'
import { Route as LangLangIndexRouteImport } from './routes/$lang/_lang/index'
import { Route as LangLangResetPasswordRouteImport } from './routes/$lang/_lang/reset-password'
import { Route as LangLangLoginRouteImport } from './routes/$lang/_lang/login'
import { Route as LangLangForgotPasswordRouteImport } from './routes/$lang/_lang/forgot-password'
import { Route as LangLangAuthRouteImport } from './routes/$lang/_lang/_auth'
import { Route as LangLangAuthTestFormRouteImport } from './routes/$lang/_lang/_auth/testForm'
import { Route as LangLangAuthGlossaryRouteImport } from './routes/$lang/_lang/_auth/glossary'
import { Route as LangLangAuthDashboardRouteImport } from './routes/$lang/_lang/_auth/dashboard'
import { Route as LangLangAuthProfileRouteRouteImport } from './routes/$lang/_lang/_auth/profile/route'
import { Route as LangLangAuthLocalLegislationsRouteRouteImport } from './routes/$lang/_lang/_auth/local-legislations/route'
import { Route as LangLangAuthLocalDecisionsRouteRouteImport } from './routes/$lang/_lang/_auth/local-decisions/route'
import { Route as LangLangAuthInternationalTreatiesRouteRouteImport } from './routes/$lang/_lang/_auth/international-treaties/route'
import { Route as LangLangAuthFederalLegislationsRouteRouteImport } from './routes/$lang/_lang/_auth/federal-legislations/route'
import { Route as LangLangAuthFederalDecisionsRouteRouteImport } from './routes/$lang/_lang/_auth/federal-decisions/route'
import { Route as LangLangAuthProfileIndexRouteImport } from './routes/$lang/_lang/_auth/profile/index'
import { Route as LangLangAuthLocalLegislationsIndexRouteImport } from './routes/$lang/_lang/_auth/local-legislations/index'
import { Route as LangLangAuthLocalDecisionsIndexRouteImport } from './routes/$lang/_lang/_auth/local-decisions/index'
import { Route as LangLangAuthInternationalTreatiesIndexRouteImport } from './routes/$lang/_lang/_auth/international-treaties/index'
import { Route as LangLangAuthFederalLegislationsIndexRouteImport } from './routes/$lang/_lang/_auth/federal-legislations/index'
import { Route as LangLangAuthFederalDecisionsIndexRouteImport } from './routes/$lang/_lang/_auth/federal-decisions/index'
import { Route as LangLangAuthLocalLegislationsAddRouteImport } from './routes/$lang/_lang/_auth/local-legislations/add'
import { Route as LangLangAuthLocalDecisionsAddRouteImport } from './routes/$lang/_lang/_auth/local-decisions/add'
import { Route as LangLangAuthInternationalTreatiesAddRouteImport } from './routes/$lang/_lang/_auth/international-treaties/add'
import { Route as LangLangAuthFederalLegislationsAddRouteImport } from './routes/$lang/_lang/_auth/federal-legislations/add'
import { Route as LangLangAuthFederalDecisionsAddRouteImport } from './routes/$lang/_lang/_auth/federal-decisions/add'
import { Route as LangLangAuthLocalLegislationsViewSlugRouteImport } from './routes/$lang/_lang/_auth/local-legislations/view.$slug'
import { Route as LangLangAuthLocalLegislationsModificationsSlugRouteImport } from './routes/$lang/_lang/_auth/local-legislations/modifications/$slug'
import { Route as LangLangAuthLocalLegislationsEditSlugRouteImport } from './routes/$lang/_lang/_auth/local-legislations/edit.$slug'
import { Route as LangLangAuthLocalDecisionsViewSlugRouteImport } from './routes/$lang/_lang/_auth/local-decisions/view.$slug'
import { Route as LangLangAuthLocalDecisionsEditSlugRouteImport } from './routes/$lang/_lang/_auth/local-decisions/edit.$slug'
import { Route as LangLangAuthInternationalTreatiesViewSlugRouteImport } from './routes/$lang/_lang/_auth/international-treaties/view.$slug'
import { Route as LangLangAuthInternationalTreatiesEditSlugRouteImport } from './routes/$lang/_lang/_auth/international-treaties/edit.$slug'
import { Route as LangLangAuthFederalLegislationsViewSlugRouteImport } from './routes/$lang/_lang/_auth/federal-legislations/view.$slug'
import { Route as LangLangAuthFederalLegislationsModificationsSlugRouteImport } from './routes/$lang/_lang/_auth/federal-legislations/modifications/$slug'
import { Route as LangLangAuthFederalLegislationsEditSlugRouteImport } from './routes/$lang/_lang/_auth/federal-legislations/edit.$slug'
import { Route as LangLangAuthFederalDecisionsViewSlugRouteImport } from './routes/$lang/_lang/_auth/federal-decisions/view.$slug'
import { Route as LangLangAuthFederalDecisionsEditSlugRouteImport } from './routes/$lang/_lang/_auth/federal-decisions/edit.$slug'
import { Route as LangLangAuthLocalLegislationsModificationsViewSlugRouteImport } from './routes/$lang/_lang/_auth/local-legislations/modifications/view.$slug'
import { Route as LangLangAuthLocalLegislationsModificationsEditSlugRouteImport } from './routes/$lang/_lang/_auth/local-legislations/modifications/edit.$slug'
import { Route as LangLangAuthLocalLegislationsModificationsAddSlugRouteImport } from './routes/$lang/_lang/_auth/local-legislations/modifications/add.$slug'
import { Route as LangLangAuthFederalLegislationsModificationsViewSlugRouteImport } from './routes/$lang/_lang/_auth/federal-legislations/modifications/view.$slug'
import { Route as LangLangAuthFederalLegislationsModificationsEditSlugRouteImport } from './routes/$lang/_lang/_auth/federal-legislations/modifications/edit.$slug'
import { Route as LangLangAuthFederalLegislationsModificationsAddSlugRouteImport } from './routes/$lang/_lang/_auth/federal-legislations/modifications/add.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLangRoute = LangLangRouteImport.update({
  id: '/$lang/_lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLangIndexRoute = LangLangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangLangRoute,
} as any)
const LangLangResetPasswordRoute = LangLangResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LangLangRoute,
} as any)
const LangLangLoginRoute = LangLangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangLangRoute,
} as any)
const LangLangForgotPasswordRoute = LangLangForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LangLangRoute,
} as any)
const LangLangAuthRoute = LangLangAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LangLangRoute,
} as any)
const LangLangAuthTestFormRoute = LangLangAuthTestFormRouteImport.update({
  id: '/testForm',
  path: '/testForm',
  getParentRoute: () => LangLangAuthRoute,
} as any)
const LangLangAuthGlossaryRoute = LangLangAuthGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => LangLangAuthRoute,
} as any)
const LangLangAuthDashboardRoute = LangLangAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangLangAuthRoute,
} as any)
const LangLangAuthProfileRouteRoute =
  LangLangAuthProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LangLangAuthRoute,
  } as any)
const LangLangAuthLocalLegislationsRouteRoute =
  LangLangAuthLocalLegislationsRouteRouteImport.update({
    id: '/local-legislations',
    path: '/local-legislations',
    getParentRoute: () => LangLangAuthRoute,
  } as any)
const LangLangAuthLocalDecisionsRouteRoute =
  LangLangAuthLocalDecisionsRouteRouteImport.update({
    id: '/local-decisions',
    path: '/local-decisions',
    getParentRoute: () => LangLangAuthRoute,
  } as any)
const LangLangAuthInternationalTreatiesRouteRoute =
  LangLangAuthInternationalTreatiesRouteRouteImport.update({
    id: '/international-treaties',
    path: '/international-treaties',
    getParentRoute: () => LangLangAuthRoute,
  } as any)
const LangLangAuthFederalLegislationsRouteRoute =
  LangLangAuthFederalLegislationsRouteRouteImport.update({
    id: '/federal-legislations',
    path: '/federal-legislations',
    getParentRoute: () => LangLangAuthRoute,
  } as any)
const LangLangAuthFederalDecisionsRouteRoute =
  LangLangAuthFederalDecisionsRouteRouteImport.update({
    id: '/federal-decisions',
    path: '/federal-decisions',
    getParentRoute: () => LangLangAuthRoute,
  } as any)
const LangLangAuthProfileIndexRoute =
  LangLangAuthProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangLangAuthProfileRouteRoute,
  } as any)
const LangLangAuthLocalLegislationsIndexRoute =
  LangLangAuthLocalLegislationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangLangAuthLocalLegislationsRouteRoute,
  } as any)
const LangLangAuthLocalDecisionsIndexRoute =
  LangLangAuthLocalDecisionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangLangAuthLocalDecisionsRouteRoute,
  } as any)
const LangLangAuthInternationalTreatiesIndexRoute =
  LangLangAuthInternationalTreatiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangLangAuthInternationalTreatiesRouteRoute,
  } as any)
const LangLangAuthFederalLegislationsIndexRoute =
  LangLangAuthFederalLegislationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangLangAuthFederalLegislationsRouteRoute,
  } as any)
const LangLangAuthFederalDecisionsIndexRoute =
  LangLangAuthFederalDecisionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangLangAuthFederalDecisionsRouteRoute,
  } as any)
const LangLangAuthLocalLegislationsAddRoute =
  LangLangAuthLocalLegislationsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => LangLangAuthLocalLegislationsRouteRoute,
  } as any)
const LangLangAuthLocalDecisionsAddRoute =
  LangLangAuthLocalDecisionsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => LangLangAuthLocalDecisionsRouteRoute,
  } as any)
const LangLangAuthInternationalTreatiesAddRoute =
  LangLangAuthInternationalTreatiesAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => LangLangAuthInternationalTreatiesRouteRoute,
  } as any)
const LangLangAuthFederalLegislationsAddRoute =
  LangLangAuthFederalLegislationsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => LangLangAuthFederalLegislationsRouteRoute,
  } as any)
const LangLangAuthFederalDecisionsAddRoute =
  LangLangAuthFederalDecisionsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => LangLangAuthFederalDecisionsRouteRoute,
  } as any)
const LangLangAuthLocalLegislationsViewSlugRoute =
  LangLangAuthLocalLegislationsViewSlugRouteImport.update({
    id: '/view/$slug',
    path: '/view/$slug',
    getParentRoute: () => LangLangAuthLocalLegislationsRouteRoute,
  } as any)
const LangLangAuthLocalLegislationsModificationsSlugRoute =
  LangLangAuthLocalLegislationsModificationsSlugRouteImport.update({
    id: '/modifications/$slug',
    path: '/modifications/$slug',
    getParentRoute: () => LangLangAuthLocalLegislationsRouteRoute,
  } as any)
const LangLangAuthLocalLegislationsEditSlugRoute =
  LangLangAuthLocalLegislationsEditSlugRouteImport.update({
    id: '/edit/$slug',
    path: '/edit/$slug',
    getParentRoute: () => LangLangAuthLocalLegislationsRouteRoute,
  } as any)
const LangLangAuthLocalDecisionsViewSlugRoute =
  LangLangAuthLocalDecisionsViewSlugRouteImport.update({
    id: '/view/$slug',
    path: '/view/$slug',
    getParentRoute: () => LangLangAuthLocalDecisionsRouteRoute,
  } as any)
const LangLangAuthLocalDecisionsEditSlugRoute =
  LangLangAuthLocalDecisionsEditSlugRouteImport.update({
    id: '/edit/$slug',
    path: '/edit/$slug',
    getParentRoute: () => LangLangAuthLocalDecisionsRouteRoute,
  } as any)
const LangLangAuthInternationalTreatiesViewSlugRoute =
  LangLangAuthInternationalTreatiesViewSlugRouteImport.update({
    id: '/view/$slug',
    path: '/view/$slug',
    getParentRoute: () => LangLangAuthInternationalTreatiesRouteRoute,
  } as any)
const LangLangAuthInternationalTreatiesEditSlugRoute =
  LangLangAuthInternationalTreatiesEditSlugRouteImport.update({
    id: '/edit/$slug',
    path: '/edit/$slug',
    getParentRoute: () => LangLangAuthInternationalTreatiesRouteRoute,
  } as any)
const LangLangAuthFederalLegislationsViewSlugRoute =
  LangLangAuthFederalLegislationsViewSlugRouteImport.update({
    id: '/view/$slug',
    path: '/view/$slug',
    getParentRoute: () => LangLangAuthFederalLegislationsRouteRoute,
  } as any)
const LangLangAuthFederalLegislationsModificationsSlugRoute =
  LangLangAuthFederalLegislationsModificationsSlugRouteImport.update({
    id: '/modifications/$slug',
    path: '/modifications/$slug',
    getParentRoute: () => LangLangAuthFederalLegislationsRouteRoute,
  } as any)
const LangLangAuthFederalLegislationsEditSlugRoute =
  LangLangAuthFederalLegislationsEditSlugRouteImport.update({
    id: '/edit/$slug',
    path: '/edit/$slug',
    getParentRoute: () => LangLangAuthFederalLegislationsRouteRoute,
  } as any)
const LangLangAuthFederalDecisionsViewSlugRoute =
  LangLangAuthFederalDecisionsViewSlugRouteImport.update({
    id: '/view/$slug',
    path: '/view/$slug',
    getParentRoute: () => LangLangAuthFederalDecisionsRouteRoute,
  } as any)
const LangLangAuthFederalDecisionsEditSlugRoute =
  LangLangAuthFederalDecisionsEditSlugRouteImport.update({
    id: '/edit/$slug',
    path: '/edit/$slug',
    getParentRoute: () => LangLangAuthFederalDecisionsRouteRoute,
  } as any)
const LangLangAuthLocalLegislationsModificationsViewSlugRoute =
  LangLangAuthLocalLegislationsModificationsViewSlugRouteImport.update({
    id: '/modifications/view/$slug',
    path: '/modifications/view/$slug',
    getParentRoute: () => LangLangAuthLocalLegislationsRouteRoute,
  } as any)
const LangLangAuthLocalLegislationsModificationsEditSlugRoute =
  LangLangAuthLocalLegislationsModificationsEditSlugRouteImport.update({
    id: '/modifications/edit/$slug',
    path: '/modifications/edit/$slug',
    getParentRoute: () => LangLangAuthLocalLegislationsRouteRoute,
  } as any)
const LangLangAuthLocalLegislationsModificationsAddSlugRoute =
  LangLangAuthLocalLegislationsModificationsAddSlugRouteImport.update({
    id: '/modifications/add/$slug',
    path: '/modifications/add/$slug',
    getParentRoute: () => LangLangAuthLocalLegislationsRouteRoute,
  } as any)
const LangLangAuthFederalLegislationsModificationsViewSlugRoute =
  LangLangAuthFederalLegislationsModificationsViewSlugRouteImport.update({
    id: '/modifications/view/$slug',
    path: '/modifications/view/$slug',
    getParentRoute: () => LangLangAuthFederalLegislationsRouteRoute,
  } as any)
const LangLangAuthFederalLegislationsModificationsEditSlugRoute =
  LangLangAuthFederalLegislationsModificationsEditSlugRouteImport.update({
    id: '/modifications/edit/$slug',
    path: '/modifications/edit/$slug',
    getParentRoute: () => LangLangAuthFederalLegislationsRouteRoute,
  } as any)
const LangLangAuthFederalLegislationsModificationsAddSlugRoute =
  LangLangAuthFederalLegislationsModificationsAddSlugRouteImport.update({
    id: '/modifications/add/$slug',
    path: '/modifications/add/$slug',
    getParentRoute: () => LangLangAuthFederalLegislationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangLangAuthRouteWithChildren
  '/$lang/forgot-password': typeof LangLangForgotPasswordRoute
  '/$lang/login': typeof LangLangLoginRoute
  '/$lang/reset-password': typeof LangLangResetPasswordRoute
  '/$lang/': typeof LangLangIndexRoute
  '/$lang/federal-decisions': typeof LangLangAuthFederalDecisionsRouteRouteWithChildren
  '/$lang/federal-legislations': typeof LangLangAuthFederalLegislationsRouteRouteWithChildren
  '/$lang/international-treaties': typeof LangLangAuthInternationalTreatiesRouteRouteWithChildren
  '/$lang/local-decisions': typeof LangLangAuthLocalDecisionsRouteRouteWithChildren
  '/$lang/local-legislations': typeof LangLangAuthLocalLegislationsRouteRouteWithChildren
  '/$lang/profile': typeof LangLangAuthProfileRouteRouteWithChildren
  '/$lang/dashboard': typeof LangLangAuthDashboardRoute
  '/$lang/glossary': typeof LangLangAuthGlossaryRoute
  '/$lang/testForm': typeof LangLangAuthTestFormRoute
  '/$lang/federal-decisions/add': typeof LangLangAuthFederalDecisionsAddRoute
  '/$lang/federal-legislations/add': typeof LangLangAuthFederalLegislationsAddRoute
  '/$lang/international-treaties/add': typeof LangLangAuthInternationalTreatiesAddRoute
  '/$lang/local-decisions/add': typeof LangLangAuthLocalDecisionsAddRoute
  '/$lang/local-legislations/add': typeof LangLangAuthLocalLegislationsAddRoute
  '/$lang/federal-decisions/': typeof LangLangAuthFederalDecisionsIndexRoute
  '/$lang/federal-legislations/': typeof LangLangAuthFederalLegislationsIndexRoute
  '/$lang/international-treaties/': typeof LangLangAuthInternationalTreatiesIndexRoute
  '/$lang/local-decisions/': typeof LangLangAuthLocalDecisionsIndexRoute
  '/$lang/local-legislations/': typeof LangLangAuthLocalLegislationsIndexRoute
  '/$lang/profile/': typeof LangLangAuthProfileIndexRoute
  '/$lang/federal-decisions/edit/$slug': typeof LangLangAuthFederalDecisionsEditSlugRoute
  '/$lang/federal-decisions/view/$slug': typeof LangLangAuthFederalDecisionsViewSlugRoute
  '/$lang/federal-legislations/edit/$slug': typeof LangLangAuthFederalLegislationsEditSlugRoute
  '/$lang/federal-legislations/modifications/$slug': typeof LangLangAuthFederalLegislationsModificationsSlugRoute
  '/$lang/federal-legislations/view/$slug': typeof LangLangAuthFederalLegislationsViewSlugRoute
  '/$lang/international-treaties/edit/$slug': typeof LangLangAuthInternationalTreatiesEditSlugRoute
  '/$lang/international-treaties/view/$slug': typeof LangLangAuthInternationalTreatiesViewSlugRoute
  '/$lang/local-decisions/edit/$slug': typeof LangLangAuthLocalDecisionsEditSlugRoute
  '/$lang/local-decisions/view/$slug': typeof LangLangAuthLocalDecisionsViewSlugRoute
  '/$lang/local-legislations/edit/$slug': typeof LangLangAuthLocalLegislationsEditSlugRoute
  '/$lang/local-legislations/modifications/$slug': typeof LangLangAuthLocalLegislationsModificationsSlugRoute
  '/$lang/local-legislations/view/$slug': typeof LangLangAuthLocalLegislationsViewSlugRoute
  '/$lang/federal-legislations/modifications/add/$slug': typeof LangLangAuthFederalLegislationsModificationsAddSlugRoute
  '/$lang/federal-legislations/modifications/edit/$slug': typeof LangLangAuthFederalLegislationsModificationsEditSlugRoute
  '/$lang/federal-legislations/modifications/view/$slug': typeof LangLangAuthFederalLegislationsModificationsViewSlugRoute
  '/$lang/local-legislations/modifications/add/$slug': typeof LangLangAuthLocalLegislationsModificationsAddSlugRoute
  '/$lang/local-legislations/modifications/edit/$slug': typeof LangLangAuthLocalLegislationsModificationsEditSlugRoute
  '/$lang/local-legislations/modifications/view/$slug': typeof LangLangAuthLocalLegislationsModificationsViewSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangLangIndexRoute
  '/$lang/forgot-password': typeof LangLangForgotPasswordRoute
  '/$lang/login': typeof LangLangLoginRoute
  '/$lang/reset-password': typeof LangLangResetPasswordRoute
  '/$lang/dashboard': typeof LangLangAuthDashboardRoute
  '/$lang/glossary': typeof LangLangAuthGlossaryRoute
  '/$lang/testForm': typeof LangLangAuthTestFormRoute
  '/$lang/federal-decisions/add': typeof LangLangAuthFederalDecisionsAddRoute
  '/$lang/federal-legislations/add': typeof LangLangAuthFederalLegislationsAddRoute
  '/$lang/international-treaties/add': typeof LangLangAuthInternationalTreatiesAddRoute
  '/$lang/local-decisions/add': typeof LangLangAuthLocalDecisionsAddRoute
  '/$lang/local-legislations/add': typeof LangLangAuthLocalLegislationsAddRoute
  '/$lang/federal-decisions': typeof LangLangAuthFederalDecisionsIndexRoute
  '/$lang/federal-legislations': typeof LangLangAuthFederalLegislationsIndexRoute
  '/$lang/international-treaties': typeof LangLangAuthInternationalTreatiesIndexRoute
  '/$lang/local-decisions': typeof LangLangAuthLocalDecisionsIndexRoute
  '/$lang/local-legislations': typeof LangLangAuthLocalLegislationsIndexRoute
  '/$lang/profile': typeof LangLangAuthProfileIndexRoute
  '/$lang/federal-decisions/edit/$slug': typeof LangLangAuthFederalDecisionsEditSlugRoute
  '/$lang/federal-decisions/view/$slug': typeof LangLangAuthFederalDecisionsViewSlugRoute
  '/$lang/federal-legislations/edit/$slug': typeof LangLangAuthFederalLegislationsEditSlugRoute
  '/$lang/federal-legislations/modifications/$slug': typeof LangLangAuthFederalLegislationsModificationsSlugRoute
  '/$lang/federal-legislations/view/$slug': typeof LangLangAuthFederalLegislationsViewSlugRoute
  '/$lang/international-treaties/edit/$slug': typeof LangLangAuthInternationalTreatiesEditSlugRoute
  '/$lang/international-treaties/view/$slug': typeof LangLangAuthInternationalTreatiesViewSlugRoute
  '/$lang/local-decisions/edit/$slug': typeof LangLangAuthLocalDecisionsEditSlugRoute
  '/$lang/local-decisions/view/$slug': typeof LangLangAuthLocalDecisionsViewSlugRoute
  '/$lang/local-legislations/edit/$slug': typeof LangLangAuthLocalLegislationsEditSlugRoute
  '/$lang/local-legislations/modifications/$slug': typeof LangLangAuthLocalLegislationsModificationsSlugRoute
  '/$lang/local-legislations/view/$slug': typeof LangLangAuthLocalLegislationsViewSlugRoute
  '/$lang/federal-legislations/modifications/add/$slug': typeof LangLangAuthFederalLegislationsModificationsAddSlugRoute
  '/$lang/federal-legislations/modifications/edit/$slug': typeof LangLangAuthFederalLegislationsModificationsEditSlugRoute
  '/$lang/federal-legislations/modifications/view/$slug': typeof LangLangAuthFederalLegislationsModificationsViewSlugRoute
  '/$lang/local-legislations/modifications/add/$slug': typeof LangLangAuthLocalLegislationsModificationsAddSlugRoute
  '/$lang/local-legislations/modifications/edit/$slug': typeof LangLangAuthLocalLegislationsModificationsEditSlugRoute
  '/$lang/local-legislations/modifications/view/$slug': typeof LangLangAuthLocalLegislationsModificationsViewSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang/_lang': typeof LangLangRouteWithChildren
  '/$lang/_lang/_auth': typeof LangLangAuthRouteWithChildren
  '/$lang/_lang/forgot-password': typeof LangLangForgotPasswordRoute
  '/$lang/_lang/login': typeof LangLangLoginRoute
  '/$lang/_lang/reset-password': typeof LangLangResetPasswordRoute
  '/$lang/_lang/': typeof LangLangIndexRoute
  '/$lang/_lang/_auth/federal-decisions': typeof LangLangAuthFederalDecisionsRouteRouteWithChildren
  '/$lang/_lang/_auth/federal-legislations': typeof LangLangAuthFederalLegislationsRouteRouteWithChildren
  '/$lang/_lang/_auth/international-treaties': typeof LangLangAuthInternationalTreatiesRouteRouteWithChildren
  '/$lang/_lang/_auth/local-decisions': typeof LangLangAuthLocalDecisionsRouteRouteWithChildren
  '/$lang/_lang/_auth/local-legislations': typeof LangLangAuthLocalLegislationsRouteRouteWithChildren
  '/$lang/_lang/_auth/profile': typeof LangLangAuthProfileRouteRouteWithChildren
  '/$lang/_lang/_auth/dashboard': typeof LangLangAuthDashboardRoute
  '/$lang/_lang/_auth/glossary': typeof LangLangAuthGlossaryRoute
  '/$lang/_lang/_auth/testForm': typeof LangLangAuthTestFormRoute
  '/$lang/_lang/_auth/federal-decisions/add': typeof LangLangAuthFederalDecisionsAddRoute
  '/$lang/_lang/_auth/federal-legislations/add': typeof LangLangAuthFederalLegislationsAddRoute
  '/$lang/_lang/_auth/international-treaties/add': typeof LangLangAuthInternationalTreatiesAddRoute
  '/$lang/_lang/_auth/local-decisions/add': typeof LangLangAuthLocalDecisionsAddRoute
  '/$lang/_lang/_auth/local-legislations/add': typeof LangLangAuthLocalLegislationsAddRoute
  '/$lang/_lang/_auth/federal-decisions/': typeof LangLangAuthFederalDecisionsIndexRoute
  '/$lang/_lang/_auth/federal-legislations/': typeof LangLangAuthFederalLegislationsIndexRoute
  '/$lang/_lang/_auth/international-treaties/': typeof LangLangAuthInternationalTreatiesIndexRoute
  '/$lang/_lang/_auth/local-decisions/': typeof LangLangAuthLocalDecisionsIndexRoute
  '/$lang/_lang/_auth/local-legislations/': typeof LangLangAuthLocalLegislationsIndexRoute
  '/$lang/_lang/_auth/profile/': typeof LangLangAuthProfileIndexRoute
  '/$lang/_lang/_auth/federal-decisions/edit/$slug': typeof LangLangAuthFederalDecisionsEditSlugRoute
  '/$lang/_lang/_auth/federal-decisions/view/$slug': typeof LangLangAuthFederalDecisionsViewSlugRoute
  '/$lang/_lang/_auth/federal-legislations/edit/$slug': typeof LangLangAuthFederalLegislationsEditSlugRoute
  '/$lang/_lang/_auth/federal-legislations/modifications/$slug': typeof LangLangAuthFederalLegislationsModificationsSlugRoute
  '/$lang/_lang/_auth/federal-legislations/view/$slug': typeof LangLangAuthFederalLegislationsViewSlugRoute
  '/$lang/_lang/_auth/international-treaties/edit/$slug': typeof LangLangAuthInternationalTreatiesEditSlugRoute
  '/$lang/_lang/_auth/international-treaties/view/$slug': typeof LangLangAuthInternationalTreatiesViewSlugRoute
  '/$lang/_lang/_auth/local-decisions/edit/$slug': typeof LangLangAuthLocalDecisionsEditSlugRoute
  '/$lang/_lang/_auth/local-decisions/view/$slug': typeof LangLangAuthLocalDecisionsViewSlugRoute
  '/$lang/_lang/_auth/local-legislations/edit/$slug': typeof LangLangAuthLocalLegislationsEditSlugRoute
  '/$lang/_lang/_auth/local-legislations/modifications/$slug': typeof LangLangAuthLocalLegislationsModificationsSlugRoute
  '/$lang/_lang/_auth/local-legislations/view/$slug': typeof LangLangAuthLocalLegislationsViewSlugRoute
  '/$lang/_lang/_auth/federal-legislations/modifications/add/$slug': typeof LangLangAuthFederalLegislationsModificationsAddSlugRoute
  '/$lang/_lang/_auth/federal-legislations/modifications/edit/$slug': typeof LangLangAuthFederalLegislationsModificationsEditSlugRoute
  '/$lang/_lang/_auth/federal-legislations/modifications/view/$slug': typeof LangLangAuthFederalLegislationsModificationsViewSlugRoute
  '/$lang/_lang/_auth/local-legislations/modifications/add/$slug': typeof LangLangAuthLocalLegislationsModificationsAddSlugRoute
  '/$lang/_lang/_auth/local-legislations/modifications/edit/$slug': typeof LangLangAuthLocalLegislationsModificationsEditSlugRoute
  '/$lang/_lang/_auth/local-legislations/modifications/view/$slug': typeof LangLangAuthLocalLegislationsModificationsViewSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/forgot-password'
    | '/$lang/login'
    | '/$lang/reset-password'
    | '/$lang/'
    | '/$lang/federal-decisions'
    | '/$lang/federal-legislations'
    | '/$lang/international-treaties'
    | '/$lang/local-decisions'
    | '/$lang/local-legislations'
    | '/$lang/profile'
    | '/$lang/dashboard'
    | '/$lang/glossary'
    | '/$lang/testForm'
    | '/$lang/federal-decisions/add'
    | '/$lang/federal-legislations/add'
    | '/$lang/international-treaties/add'
    | '/$lang/local-decisions/add'
    | '/$lang/local-legislations/add'
    | '/$lang/federal-decisions/'
    | '/$lang/federal-legislations/'
    | '/$lang/international-treaties/'
    | '/$lang/local-decisions/'
    | '/$lang/local-legislations/'
    | '/$lang/profile/'
    | '/$lang/federal-decisions/edit/$slug'
    | '/$lang/federal-decisions/view/$slug'
    | '/$lang/federal-legislations/edit/$slug'
    | '/$lang/federal-legislations/modifications/$slug'
    | '/$lang/federal-legislations/view/$slug'
    | '/$lang/international-treaties/edit/$slug'
    | '/$lang/international-treaties/view/$slug'
    | '/$lang/local-decisions/edit/$slug'
    | '/$lang/local-decisions/view/$slug'
    | '/$lang/local-legislations/edit/$slug'
    | '/$lang/local-legislations/modifications/$slug'
    | '/$lang/local-legislations/view/$slug'
    | '/$lang/federal-legislations/modifications/add/$slug'
    | '/$lang/federal-legislations/modifications/edit/$slug'
    | '/$lang/federal-legislations/modifications/view/$slug'
    | '/$lang/local-legislations/modifications/add/$slug'
    | '/$lang/local-legislations/modifications/edit/$slug'
    | '/$lang/local-legislations/modifications/view/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/forgot-password'
    | '/$lang/login'
    | '/$lang/reset-password'
    | '/$lang/dashboard'
    | '/$lang/glossary'
    | '/$lang/testForm'
    | '/$lang/federal-decisions/add'
    | '/$lang/federal-legislations/add'
    | '/$lang/international-treaties/add'
    | '/$lang/local-decisions/add'
    | '/$lang/local-legislations/add'
    | '/$lang/federal-decisions'
    | '/$lang/federal-legislations'
    | '/$lang/international-treaties'
    | '/$lang/local-decisions'
    | '/$lang/local-legislations'
    | '/$lang/profile'
    | '/$lang/federal-decisions/edit/$slug'
    | '/$lang/federal-decisions/view/$slug'
    | '/$lang/federal-legislations/edit/$slug'
    | '/$lang/federal-legislations/modifications/$slug'
    | '/$lang/federal-legislations/view/$slug'
    | '/$lang/international-treaties/edit/$slug'
    | '/$lang/international-treaties/view/$slug'
    | '/$lang/local-decisions/edit/$slug'
    | '/$lang/local-decisions/view/$slug'
    | '/$lang/local-legislations/edit/$slug'
    | '/$lang/local-legislations/modifications/$slug'
    | '/$lang/local-legislations/view/$slug'
    | '/$lang/federal-legislations/modifications/add/$slug'
    | '/$lang/federal-legislations/modifications/edit/$slug'
    | '/$lang/federal-legislations/modifications/view/$slug'
    | '/$lang/local-legislations/modifications/add/$slug'
    | '/$lang/local-legislations/modifications/edit/$slug'
    | '/$lang/local-legislations/modifications/view/$slug'
  id:
    | '__root__'
    | '/'
    | '/$lang/_lang'
    | '/$lang/_lang/_auth'
    | '/$lang/_lang/forgot-password'
    | '/$lang/_lang/login'
    | '/$lang/_lang/reset-password'
    | '/$lang/_lang/'
    | '/$lang/_lang/_auth/federal-decisions'
    | '/$lang/_lang/_auth/federal-legislations'
    | '/$lang/_lang/_auth/international-treaties'
    | '/$lang/_lang/_auth/local-decisions'
    | '/$lang/_lang/_auth/local-legislations'
    | '/$lang/_lang/_auth/profile'
    | '/$lang/_lang/_auth/dashboard'
    | '/$lang/_lang/_auth/glossary'
    | '/$lang/_lang/_auth/testForm'
    | '/$lang/_lang/_auth/federal-decisions/add'
    | '/$lang/_lang/_auth/federal-legislations/add'
    | '/$lang/_lang/_auth/international-treaties/add'
    | '/$lang/_lang/_auth/local-decisions/add'
    | '/$lang/_lang/_auth/local-legislations/add'
    | '/$lang/_lang/_auth/federal-decisions/'
    | '/$lang/_lang/_auth/federal-legislations/'
    | '/$lang/_lang/_auth/international-treaties/'
    | '/$lang/_lang/_auth/local-decisions/'
    | '/$lang/_lang/_auth/local-legislations/'
    | '/$lang/_lang/_auth/profile/'
    | '/$lang/_lang/_auth/federal-decisions/edit/$slug'
    | '/$lang/_lang/_auth/federal-decisions/view/$slug'
    | '/$lang/_lang/_auth/federal-legislations/edit/$slug'
    | '/$lang/_lang/_auth/federal-legislations/modifications/$slug'
    | '/$lang/_lang/_auth/federal-legislations/view/$slug'
    | '/$lang/_lang/_auth/international-treaties/edit/$slug'
    | '/$lang/_lang/_auth/international-treaties/view/$slug'
    | '/$lang/_lang/_auth/local-decisions/edit/$slug'
    | '/$lang/_lang/_auth/local-decisions/view/$slug'
    | '/$lang/_lang/_auth/local-legislations/edit/$slug'
    | '/$lang/_lang/_auth/local-legislations/modifications/$slug'
    | '/$lang/_lang/_auth/local-legislations/view/$slug'
    | '/$lang/_lang/_auth/federal-legislations/modifications/add/$slug'
    | '/$lang/_lang/_auth/federal-legislations/modifications/edit/$slug'
    | '/$lang/_lang/_auth/federal-legislations/modifications/view/$slug'
    | '/$lang/_lang/_auth/local-legislations/modifications/add/$slug'
    | '/$lang/_lang/_auth/local-legislations/modifications/edit/$slug'
    | '/$lang/_lang/_auth/local-legislations/modifications/view/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangLangRoute: typeof LangLangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/_lang': {
      id: '/$lang/_lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/_lang/': {
      id: '/$lang/_lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangLangIndexRouteImport
      parentRoute: typeof LangLangRoute
    }
    '/$lang/_lang/reset-password': {
      id: '/$lang/_lang/reset-password'
      path: '/reset-password'
      fullPath: '/$lang/reset-password'
      preLoaderRoute: typeof LangLangResetPasswordRouteImport
      parentRoute: typeof LangLangRoute
    }
    '/$lang/_lang/login': {
      id: '/$lang/_lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLangLoginRouteImport
      parentRoute: typeof LangLangRoute
    }
    '/$lang/_lang/forgot-password': {
      id: '/$lang/_lang/forgot-password'
      path: '/forgot-password'
      fullPath: '/$lang/forgot-password'
      preLoaderRoute: typeof LangLangForgotPasswordRouteImport
      parentRoute: typeof LangLangRoute
    }
    '/$lang/_lang/_auth': {
      id: '/$lang/_lang/_auth'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangLangAuthRouteImport
      parentRoute: typeof LangLangRoute
    }
    '/$lang/_lang/_auth/testForm': {
      id: '/$lang/_lang/_auth/testForm'
      path: '/testForm'
      fullPath: '/$lang/testForm'
      preLoaderRoute: typeof LangLangAuthTestFormRouteImport
      parentRoute: typeof LangLangAuthRoute
    }
    '/$lang/_lang/_auth/glossary': {
      id: '/$lang/_lang/_auth/glossary'
      path: '/glossary'
      fullPath: '/$lang/glossary'
      preLoaderRoute: typeof LangLangAuthGlossaryRouteImport
      parentRoute: typeof LangLangAuthRoute
    }
    '/$lang/_lang/_auth/dashboard': {
      id: '/$lang/_lang/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangLangAuthDashboardRouteImport
      parentRoute: typeof LangLangAuthRoute
    }
    '/$lang/_lang/_auth/profile': {
      id: '/$lang/_lang/_auth/profile'
      path: '/profile'
      fullPath: '/$lang/profile'
      preLoaderRoute: typeof LangLangAuthProfileRouteRouteImport
      parentRoute: typeof LangLangAuthRoute
    }
    '/$lang/_lang/_auth/local-legislations': {
      id: '/$lang/_lang/_auth/local-legislations'
      path: '/local-legislations'
      fullPath: '/$lang/local-legislations'
      preLoaderRoute: typeof LangLangAuthLocalLegislationsRouteRouteImport
      parentRoute: typeof LangLangAuthRoute
    }
    '/$lang/_lang/_auth/local-decisions': {
      id: '/$lang/_lang/_auth/local-decisions'
      path: '/local-decisions'
      fullPath: '/$lang/local-decisions'
      preLoaderRoute: typeof LangLangAuthLocalDecisionsRouteRouteImport
      parentRoute: typeof LangLangAuthRoute
    }
    '/$lang/_lang/_auth/international-treaties': {
      id: '/$lang/_lang/_auth/international-treaties'
      path: '/international-treaties'
      fullPath: '/$lang/international-treaties'
      preLoaderRoute: typeof LangLangAuthInternationalTreatiesRouteRouteImport
      parentRoute: typeof LangLangAuthRoute
    }
    '/$lang/_lang/_auth/federal-legislations': {
      id: '/$lang/_lang/_auth/federal-legislations'
      path: '/federal-legislations'
      fullPath: '/$lang/federal-legislations'
      preLoaderRoute: typeof LangLangAuthFederalLegislationsRouteRouteImport
      parentRoute: typeof LangLangAuthRoute
    }
    '/$lang/_lang/_auth/federal-decisions': {
      id: '/$lang/_lang/_auth/federal-decisions'
      path: '/federal-decisions'
      fullPath: '/$lang/federal-decisions'
      preLoaderRoute: typeof LangLangAuthFederalDecisionsRouteRouteImport
      parentRoute: typeof LangLangAuthRoute
    }
    '/$lang/_lang/_auth/profile/': {
      id: '/$lang/_lang/_auth/profile/'
      path: '/'
      fullPath: '/$lang/profile/'
      preLoaderRoute: typeof LangLangAuthProfileIndexRouteImport
      parentRoute: typeof LangLangAuthProfileRouteRoute
    }
    '/$lang/_lang/_auth/local-legislations/': {
      id: '/$lang/_lang/_auth/local-legislations/'
      path: '/'
      fullPath: '/$lang/local-legislations/'
      preLoaderRoute: typeof LangLangAuthLocalLegislationsIndexRouteImport
      parentRoute: typeof LangLangAuthLocalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/local-decisions/': {
      id: '/$lang/_lang/_auth/local-decisions/'
      path: '/'
      fullPath: '/$lang/local-decisions/'
      preLoaderRoute: typeof LangLangAuthLocalDecisionsIndexRouteImport
      parentRoute: typeof LangLangAuthLocalDecisionsRouteRoute
    }
    '/$lang/_lang/_auth/international-treaties/': {
      id: '/$lang/_lang/_auth/international-treaties/'
      path: '/'
      fullPath: '/$lang/international-treaties/'
      preLoaderRoute: typeof LangLangAuthInternationalTreatiesIndexRouteImport
      parentRoute: typeof LangLangAuthInternationalTreatiesRouteRoute
    }
    '/$lang/_lang/_auth/federal-legislations/': {
      id: '/$lang/_lang/_auth/federal-legislations/'
      path: '/'
      fullPath: '/$lang/federal-legislations/'
      preLoaderRoute: typeof LangLangAuthFederalLegislationsIndexRouteImport
      parentRoute: typeof LangLangAuthFederalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/federal-decisions/': {
      id: '/$lang/_lang/_auth/federal-decisions/'
      path: '/'
      fullPath: '/$lang/federal-decisions/'
      preLoaderRoute: typeof LangLangAuthFederalDecisionsIndexRouteImport
      parentRoute: typeof LangLangAuthFederalDecisionsRouteRoute
    }
    '/$lang/_lang/_auth/local-legislations/add': {
      id: '/$lang/_lang/_auth/local-legislations/add'
      path: '/add'
      fullPath: '/$lang/local-legislations/add'
      preLoaderRoute: typeof LangLangAuthLocalLegislationsAddRouteImport
      parentRoute: typeof LangLangAuthLocalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/local-decisions/add': {
      id: '/$lang/_lang/_auth/local-decisions/add'
      path: '/add'
      fullPath: '/$lang/local-decisions/add'
      preLoaderRoute: typeof LangLangAuthLocalDecisionsAddRouteImport
      parentRoute: typeof LangLangAuthLocalDecisionsRouteRoute
    }
    '/$lang/_lang/_auth/international-treaties/add': {
      id: '/$lang/_lang/_auth/international-treaties/add'
      path: '/add'
      fullPath: '/$lang/international-treaties/add'
      preLoaderRoute: typeof LangLangAuthInternationalTreatiesAddRouteImport
      parentRoute: typeof LangLangAuthInternationalTreatiesRouteRoute
    }
    '/$lang/_lang/_auth/federal-legislations/add': {
      id: '/$lang/_lang/_auth/federal-legislations/add'
      path: '/add'
      fullPath: '/$lang/federal-legislations/add'
      preLoaderRoute: typeof LangLangAuthFederalLegislationsAddRouteImport
      parentRoute: typeof LangLangAuthFederalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/federal-decisions/add': {
      id: '/$lang/_lang/_auth/federal-decisions/add'
      path: '/add'
      fullPath: '/$lang/federal-decisions/add'
      preLoaderRoute: typeof LangLangAuthFederalDecisionsAddRouteImport
      parentRoute: typeof LangLangAuthFederalDecisionsRouteRoute
    }
    '/$lang/_lang/_auth/local-legislations/view/$slug': {
      id: '/$lang/_lang/_auth/local-legislations/view/$slug'
      path: '/view/$slug'
      fullPath: '/$lang/local-legislations/view/$slug'
      preLoaderRoute: typeof LangLangAuthLocalLegislationsViewSlugRouteImport
      parentRoute: typeof LangLangAuthLocalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/local-legislations/modifications/$slug': {
      id: '/$lang/_lang/_auth/local-legislations/modifications/$slug'
      path: '/modifications/$slug'
      fullPath: '/$lang/local-legislations/modifications/$slug'
      preLoaderRoute: typeof LangLangAuthLocalLegislationsModificationsSlugRouteImport
      parentRoute: typeof LangLangAuthLocalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/local-legislations/edit/$slug': {
      id: '/$lang/_lang/_auth/local-legislations/edit/$slug'
      path: '/edit/$slug'
      fullPath: '/$lang/local-legislations/edit/$slug'
      preLoaderRoute: typeof LangLangAuthLocalLegislationsEditSlugRouteImport
      parentRoute: typeof LangLangAuthLocalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/local-decisions/view/$slug': {
      id: '/$lang/_lang/_auth/local-decisions/view/$slug'
      path: '/view/$slug'
      fullPath: '/$lang/local-decisions/view/$slug'
      preLoaderRoute: typeof LangLangAuthLocalDecisionsViewSlugRouteImport
      parentRoute: typeof LangLangAuthLocalDecisionsRouteRoute
    }
    '/$lang/_lang/_auth/local-decisions/edit/$slug': {
      id: '/$lang/_lang/_auth/local-decisions/edit/$slug'
      path: '/edit/$slug'
      fullPath: '/$lang/local-decisions/edit/$slug'
      preLoaderRoute: typeof LangLangAuthLocalDecisionsEditSlugRouteImport
      parentRoute: typeof LangLangAuthLocalDecisionsRouteRoute
    }
    '/$lang/_lang/_auth/international-treaties/view/$slug': {
      id: '/$lang/_lang/_auth/international-treaties/view/$slug'
      path: '/view/$slug'
      fullPath: '/$lang/international-treaties/view/$slug'
      preLoaderRoute: typeof LangLangAuthInternationalTreatiesViewSlugRouteImport
      parentRoute: typeof LangLangAuthInternationalTreatiesRouteRoute
    }
    '/$lang/_lang/_auth/international-treaties/edit/$slug': {
      id: '/$lang/_lang/_auth/international-treaties/edit/$slug'
      path: '/edit/$slug'
      fullPath: '/$lang/international-treaties/edit/$slug'
      preLoaderRoute: typeof LangLangAuthInternationalTreatiesEditSlugRouteImport
      parentRoute: typeof LangLangAuthInternationalTreatiesRouteRoute
    }
    '/$lang/_lang/_auth/federal-legislations/view/$slug': {
      id: '/$lang/_lang/_auth/federal-legislations/view/$slug'
      path: '/view/$slug'
      fullPath: '/$lang/federal-legislations/view/$slug'
      preLoaderRoute: typeof LangLangAuthFederalLegislationsViewSlugRouteImport
      parentRoute: typeof LangLangAuthFederalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/federal-legislations/modifications/$slug': {
      id: '/$lang/_lang/_auth/federal-legislations/modifications/$slug'
      path: '/modifications/$slug'
      fullPath: '/$lang/federal-legislations/modifications/$slug'
      preLoaderRoute: typeof LangLangAuthFederalLegislationsModificationsSlugRouteImport
      parentRoute: typeof LangLangAuthFederalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/federal-legislations/edit/$slug': {
      id: '/$lang/_lang/_auth/federal-legislations/edit/$slug'
      path: '/edit/$slug'
      fullPath: '/$lang/federal-legislations/edit/$slug'
      preLoaderRoute: typeof LangLangAuthFederalLegislationsEditSlugRouteImport
      parentRoute: typeof LangLangAuthFederalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/federal-decisions/view/$slug': {
      id: '/$lang/_lang/_auth/federal-decisions/view/$slug'
      path: '/view/$slug'
      fullPath: '/$lang/federal-decisions/view/$slug'
      preLoaderRoute: typeof LangLangAuthFederalDecisionsViewSlugRouteImport
      parentRoute: typeof LangLangAuthFederalDecisionsRouteRoute
    }
    '/$lang/_lang/_auth/federal-decisions/edit/$slug': {
      id: '/$lang/_lang/_auth/federal-decisions/edit/$slug'
      path: '/edit/$slug'
      fullPath: '/$lang/federal-decisions/edit/$slug'
      preLoaderRoute: typeof LangLangAuthFederalDecisionsEditSlugRouteImport
      parentRoute: typeof LangLangAuthFederalDecisionsRouteRoute
    }
    '/$lang/_lang/_auth/local-legislations/modifications/view/$slug': {
      id: '/$lang/_lang/_auth/local-legislations/modifications/view/$slug'
      path: '/modifications/view/$slug'
      fullPath: '/$lang/local-legislations/modifications/view/$slug'
      preLoaderRoute: typeof LangLangAuthLocalLegislationsModificationsViewSlugRouteImport
      parentRoute: typeof LangLangAuthLocalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/local-legislations/modifications/edit/$slug': {
      id: '/$lang/_lang/_auth/local-legislations/modifications/edit/$slug'
      path: '/modifications/edit/$slug'
      fullPath: '/$lang/local-legislations/modifications/edit/$slug'
      preLoaderRoute: typeof LangLangAuthLocalLegislationsModificationsEditSlugRouteImport
      parentRoute: typeof LangLangAuthLocalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/local-legislations/modifications/add/$slug': {
      id: '/$lang/_lang/_auth/local-legislations/modifications/add/$slug'
      path: '/modifications/add/$slug'
      fullPath: '/$lang/local-legislations/modifications/add/$slug'
      preLoaderRoute: typeof LangLangAuthLocalLegislationsModificationsAddSlugRouteImport
      parentRoute: typeof LangLangAuthLocalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/federal-legislations/modifications/view/$slug': {
      id: '/$lang/_lang/_auth/federal-legislations/modifications/view/$slug'
      path: '/modifications/view/$slug'
      fullPath: '/$lang/federal-legislations/modifications/view/$slug'
      preLoaderRoute: typeof LangLangAuthFederalLegislationsModificationsViewSlugRouteImport
      parentRoute: typeof LangLangAuthFederalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/federal-legislations/modifications/edit/$slug': {
      id: '/$lang/_lang/_auth/federal-legislations/modifications/edit/$slug'
      path: '/modifications/edit/$slug'
      fullPath: '/$lang/federal-legislations/modifications/edit/$slug'
      preLoaderRoute: typeof LangLangAuthFederalLegislationsModificationsEditSlugRouteImport
      parentRoute: typeof LangLangAuthFederalLegislationsRouteRoute
    }
    '/$lang/_lang/_auth/federal-legislations/modifications/add/$slug': {
      id: '/$lang/_lang/_auth/federal-legislations/modifications/add/$slug'
      path: '/modifications/add/$slug'
      fullPath: '/$lang/federal-legislations/modifications/add/$slug'
      preLoaderRoute: typeof LangLangAuthFederalLegislationsModificationsAddSlugRouteImport
      parentRoute: typeof LangLangAuthFederalLegislationsRouteRoute
    }
  }
}

interface LangLangAuthFederalDecisionsRouteRouteChildren {
  LangLangAuthFederalDecisionsAddRoute: typeof LangLangAuthFederalDecisionsAddRoute
  LangLangAuthFederalDecisionsIndexRoute: typeof LangLangAuthFederalDecisionsIndexRoute
  LangLangAuthFederalDecisionsEditSlugRoute: typeof LangLangAuthFederalDecisionsEditSlugRoute
  LangLangAuthFederalDecisionsViewSlugRoute: typeof LangLangAuthFederalDecisionsViewSlugRoute
}

const LangLangAuthFederalDecisionsRouteRouteChildren: LangLangAuthFederalDecisionsRouteRouteChildren =
  {
    LangLangAuthFederalDecisionsAddRoute: LangLangAuthFederalDecisionsAddRoute,
    LangLangAuthFederalDecisionsIndexRoute:
      LangLangAuthFederalDecisionsIndexRoute,
    LangLangAuthFederalDecisionsEditSlugRoute:
      LangLangAuthFederalDecisionsEditSlugRoute,
    LangLangAuthFederalDecisionsViewSlugRoute:
      LangLangAuthFederalDecisionsViewSlugRoute,
  }

const LangLangAuthFederalDecisionsRouteRouteWithChildren =
  LangLangAuthFederalDecisionsRouteRoute._addFileChildren(
    LangLangAuthFederalDecisionsRouteRouteChildren,
  )

interface LangLangAuthFederalLegislationsRouteRouteChildren {
  LangLangAuthFederalLegislationsAddRoute: typeof LangLangAuthFederalLegislationsAddRoute
  LangLangAuthFederalLegislationsIndexRoute: typeof LangLangAuthFederalLegislationsIndexRoute
  LangLangAuthFederalLegislationsEditSlugRoute: typeof LangLangAuthFederalLegislationsEditSlugRoute
  LangLangAuthFederalLegislationsModificationsSlugRoute: typeof LangLangAuthFederalLegislationsModificationsSlugRoute
  LangLangAuthFederalLegislationsViewSlugRoute: typeof LangLangAuthFederalLegislationsViewSlugRoute
  LangLangAuthFederalLegislationsModificationsAddSlugRoute: typeof LangLangAuthFederalLegislationsModificationsAddSlugRoute
  LangLangAuthFederalLegislationsModificationsEditSlugRoute: typeof LangLangAuthFederalLegislationsModificationsEditSlugRoute
  LangLangAuthFederalLegislationsModificationsViewSlugRoute: typeof LangLangAuthFederalLegislationsModificationsViewSlugRoute
}

const LangLangAuthFederalLegislationsRouteRouteChildren: LangLangAuthFederalLegislationsRouteRouteChildren =
  {
    LangLangAuthFederalLegislationsAddRoute:
      LangLangAuthFederalLegislationsAddRoute,
    LangLangAuthFederalLegislationsIndexRoute:
      LangLangAuthFederalLegislationsIndexRoute,
    LangLangAuthFederalLegislationsEditSlugRoute:
      LangLangAuthFederalLegislationsEditSlugRoute,
    LangLangAuthFederalLegislationsModificationsSlugRoute:
      LangLangAuthFederalLegislationsModificationsSlugRoute,
    LangLangAuthFederalLegislationsViewSlugRoute:
      LangLangAuthFederalLegislationsViewSlugRoute,
    LangLangAuthFederalLegislationsModificationsAddSlugRoute:
      LangLangAuthFederalLegislationsModificationsAddSlugRoute,
    LangLangAuthFederalLegislationsModificationsEditSlugRoute:
      LangLangAuthFederalLegislationsModificationsEditSlugRoute,
    LangLangAuthFederalLegislationsModificationsViewSlugRoute:
      LangLangAuthFederalLegislationsModificationsViewSlugRoute,
  }

const LangLangAuthFederalLegislationsRouteRouteWithChildren =
  LangLangAuthFederalLegislationsRouteRoute._addFileChildren(
    LangLangAuthFederalLegislationsRouteRouteChildren,
  )

interface LangLangAuthInternationalTreatiesRouteRouteChildren {
  LangLangAuthInternationalTreatiesAddRoute: typeof LangLangAuthInternationalTreatiesAddRoute
  LangLangAuthInternationalTreatiesIndexRoute: typeof LangLangAuthInternationalTreatiesIndexRoute
  LangLangAuthInternationalTreatiesEditSlugRoute: typeof LangLangAuthInternationalTreatiesEditSlugRoute
  LangLangAuthInternationalTreatiesViewSlugRoute: typeof LangLangAuthInternationalTreatiesViewSlugRoute
}

const LangLangAuthInternationalTreatiesRouteRouteChildren: LangLangAuthInternationalTreatiesRouteRouteChildren =
  {
    LangLangAuthInternationalTreatiesAddRoute:
      LangLangAuthInternationalTreatiesAddRoute,
    LangLangAuthInternationalTreatiesIndexRoute:
      LangLangAuthInternationalTreatiesIndexRoute,
    LangLangAuthInternationalTreatiesEditSlugRoute:
      LangLangAuthInternationalTreatiesEditSlugRoute,
    LangLangAuthInternationalTreatiesViewSlugRoute:
      LangLangAuthInternationalTreatiesViewSlugRoute,
  }

const LangLangAuthInternationalTreatiesRouteRouteWithChildren =
  LangLangAuthInternationalTreatiesRouteRoute._addFileChildren(
    LangLangAuthInternationalTreatiesRouteRouteChildren,
  )

interface LangLangAuthLocalDecisionsRouteRouteChildren {
  LangLangAuthLocalDecisionsAddRoute: typeof LangLangAuthLocalDecisionsAddRoute
  LangLangAuthLocalDecisionsIndexRoute: typeof LangLangAuthLocalDecisionsIndexRoute
  LangLangAuthLocalDecisionsEditSlugRoute: typeof LangLangAuthLocalDecisionsEditSlugRoute
  LangLangAuthLocalDecisionsViewSlugRoute: typeof LangLangAuthLocalDecisionsViewSlugRoute
}

const LangLangAuthLocalDecisionsRouteRouteChildren: LangLangAuthLocalDecisionsRouteRouteChildren =
  {
    LangLangAuthLocalDecisionsAddRoute: LangLangAuthLocalDecisionsAddRoute,
    LangLangAuthLocalDecisionsIndexRoute: LangLangAuthLocalDecisionsIndexRoute,
    LangLangAuthLocalDecisionsEditSlugRoute:
      LangLangAuthLocalDecisionsEditSlugRoute,
    LangLangAuthLocalDecisionsViewSlugRoute:
      LangLangAuthLocalDecisionsViewSlugRoute,
  }

const LangLangAuthLocalDecisionsRouteRouteWithChildren =
  LangLangAuthLocalDecisionsRouteRoute._addFileChildren(
    LangLangAuthLocalDecisionsRouteRouteChildren,
  )

interface LangLangAuthLocalLegislationsRouteRouteChildren {
  LangLangAuthLocalLegislationsAddRoute: typeof LangLangAuthLocalLegislationsAddRoute
  LangLangAuthLocalLegislationsIndexRoute: typeof LangLangAuthLocalLegislationsIndexRoute
  LangLangAuthLocalLegislationsEditSlugRoute: typeof LangLangAuthLocalLegislationsEditSlugRoute
  LangLangAuthLocalLegislationsModificationsSlugRoute: typeof LangLangAuthLocalLegislationsModificationsSlugRoute
  LangLangAuthLocalLegislationsViewSlugRoute: typeof LangLangAuthLocalLegislationsViewSlugRoute
  LangLangAuthLocalLegislationsModificationsAddSlugRoute: typeof LangLangAuthLocalLegislationsModificationsAddSlugRoute
  LangLangAuthLocalLegislationsModificationsEditSlugRoute: typeof LangLangAuthLocalLegislationsModificationsEditSlugRoute
  LangLangAuthLocalLegislationsModificationsViewSlugRoute: typeof LangLangAuthLocalLegislationsModificationsViewSlugRoute
}

const LangLangAuthLocalLegislationsRouteRouteChildren: LangLangAuthLocalLegislationsRouteRouteChildren =
  {
    LangLangAuthLocalLegislationsAddRoute:
      LangLangAuthLocalLegislationsAddRoute,
    LangLangAuthLocalLegislationsIndexRoute:
      LangLangAuthLocalLegislationsIndexRoute,
    LangLangAuthLocalLegislationsEditSlugRoute:
      LangLangAuthLocalLegislationsEditSlugRoute,
    LangLangAuthLocalLegislationsModificationsSlugRoute:
      LangLangAuthLocalLegislationsModificationsSlugRoute,
    LangLangAuthLocalLegislationsViewSlugRoute:
      LangLangAuthLocalLegislationsViewSlugRoute,
    LangLangAuthLocalLegislationsModificationsAddSlugRoute:
      LangLangAuthLocalLegislationsModificationsAddSlugRoute,
    LangLangAuthLocalLegislationsModificationsEditSlugRoute:
      LangLangAuthLocalLegislationsModificationsEditSlugRoute,
    LangLangAuthLocalLegislationsModificationsViewSlugRoute:
      LangLangAuthLocalLegislationsModificationsViewSlugRoute,
  }

const LangLangAuthLocalLegislationsRouteRouteWithChildren =
  LangLangAuthLocalLegislationsRouteRoute._addFileChildren(
    LangLangAuthLocalLegislationsRouteRouteChildren,
  )

interface LangLangAuthProfileRouteRouteChildren {
  LangLangAuthProfileIndexRoute: typeof LangLangAuthProfileIndexRoute
}

const LangLangAuthProfileRouteRouteChildren: LangLangAuthProfileRouteRouteChildren =
  {
    LangLangAuthProfileIndexRoute: LangLangAuthProfileIndexRoute,
  }

const LangLangAuthProfileRouteRouteWithChildren =
  LangLangAuthProfileRouteRoute._addFileChildren(
    LangLangAuthProfileRouteRouteChildren,
  )

interface LangLangAuthRouteChildren {
  LangLangAuthFederalDecisionsRouteRoute: typeof LangLangAuthFederalDecisionsRouteRouteWithChildren
  LangLangAuthFederalLegislationsRouteRoute: typeof LangLangAuthFederalLegislationsRouteRouteWithChildren
  LangLangAuthInternationalTreatiesRouteRoute: typeof LangLangAuthInternationalTreatiesRouteRouteWithChildren
  LangLangAuthLocalDecisionsRouteRoute: typeof LangLangAuthLocalDecisionsRouteRouteWithChildren
  LangLangAuthLocalLegislationsRouteRoute: typeof LangLangAuthLocalLegislationsRouteRouteWithChildren
  LangLangAuthProfileRouteRoute: typeof LangLangAuthProfileRouteRouteWithChildren
  LangLangAuthDashboardRoute: typeof LangLangAuthDashboardRoute
  LangLangAuthGlossaryRoute: typeof LangLangAuthGlossaryRoute
  LangLangAuthTestFormRoute: typeof LangLangAuthTestFormRoute
}

const LangLangAuthRouteChildren: LangLangAuthRouteChildren = {
  LangLangAuthFederalDecisionsRouteRoute:
    LangLangAuthFederalDecisionsRouteRouteWithChildren,
  LangLangAuthFederalLegislationsRouteRoute:
    LangLangAuthFederalLegislationsRouteRouteWithChildren,
  LangLangAuthInternationalTreatiesRouteRoute:
    LangLangAuthInternationalTreatiesRouteRouteWithChildren,
  LangLangAuthLocalDecisionsRouteRoute:
    LangLangAuthLocalDecisionsRouteRouteWithChildren,
  LangLangAuthLocalLegislationsRouteRoute:
    LangLangAuthLocalLegislationsRouteRouteWithChildren,
  LangLangAuthProfileRouteRoute: LangLangAuthProfileRouteRouteWithChildren,
  LangLangAuthDashboardRoute: LangLangAuthDashboardRoute,
  LangLangAuthGlossaryRoute: LangLangAuthGlossaryRoute,
  LangLangAuthTestFormRoute: LangLangAuthTestFormRoute,
}

const LangLangAuthRouteWithChildren = LangLangAuthRoute._addFileChildren(
  LangLangAuthRouteChildren,
)

interface LangLangRouteChildren {
  LangLangAuthRoute: typeof LangLangAuthRouteWithChildren
  LangLangForgotPasswordRoute: typeof LangLangForgotPasswordRoute
  LangLangLoginRoute: typeof LangLangLoginRoute
  LangLangResetPasswordRoute: typeof LangLangResetPasswordRoute
  LangLangIndexRoute: typeof LangLangIndexRoute
}

const LangLangRouteChildren: LangLangRouteChildren = {
  LangLangAuthRoute: LangLangAuthRouteWithChildren,
  LangLangForgotPasswordRoute: LangLangForgotPasswordRoute,
  LangLangLoginRoute: LangLangLoginRoute,
  LangLangResetPasswordRoute: LangLangResetPasswordRoute,
  LangLangIndexRoute: LangLangIndexRoute,
}

const LangLangRouteWithChildren = LangLangRoute._addFileChildren(
  LangLangRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangLangRoute: LangLangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
